import { Instruction } from "./Instruction.ts";

export const Instructions = Object.freeze({
  Push: () => new Instruction(0x00),
  Pop: () => new Instruction(0x00),
  GoTo: (closure: Instruction) => new Instruction(0x00, closure),
  Return: () => new Instruction(0x00),
  Declare: (key: number) => new Instruction(0x00, key),
  Empty: () => new Instruction(0x00),
  EmptyArray: () => new Instruction(0x00),
  Reference: (lookFor: number) => new Instruction(0x00, lookFor),
  Bool: (value: Uint8Array) => new Instruction(0x00, ...value),
  Char: (value: Uint8Array) => new Instruction(0x00, ...value),
  Double: (value: Uint8Array) => new Instruction(0x00, ...value),
  Float: (value: Uint8Array) => new Instruction(0x00, ...value),
  Int: (value: Uint8Array) => new Instruction(0x00, ...value),
  Long: (value: Uint8Array) => new Instruction(0x00, ...value),
  String: (value: Uint8Array) => new Instruction(0x00, ...value),
  ForEach: (goTo: Instruction) => new Instruction(0x00),
  CreateTuple: () => new Instruction(0x00),
  AssignKey: (key: number) => new Instruction(0x00, key),
  "+": () => new Instruction(0x00),
  "-": () => new Instruction(0x00),
  "/": () => new Instruction(0x00),
  "*": () => new Instruction(0x00),
  "&&": () => new Instruction(0x00),
  "==": () => new Instruction(0x00),
  ">": () => new Instruction(0x00),
  ">=": () => new Instruction(0x00),
  "<": () => new Instruction(0x00),
  "<=": () => new Instruction(0x00),
  "!=": () => new Instruction(0x00),
  "||": () => new Instruction(0x00),
  "->": () => new Instruction(0x00),
  "++": () => new Instruction(0x00),
  ":?": (shape: Uint8Array) => new Instruction(0x00, ...shape),
  ".": (key: number) => new Instruction(0x00, key),
  "?:": (positive: Instruction, negative: Instruction) => new Instruction(0x00, positive, negative),
});
