name: Publish Compiler
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version: '26.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run typecheck -w @cinderblock-lang/compiler
      - run: npm run test -w @cinderblock-lang/tests
      - run: npm publish -w @cinderblock-lang/compiler
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish -w @cinderblock-lang/server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}